
package com.iasri.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://ws.iasri.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "greeting", targetNamespace = "http://ws.iasri.com/", className = "com.iasri.client.Greeting")
    @ResponseWrapper(localName = "greetingResponse", targetNamespace = "http://ws.iasri.com/", className = "com.iasri.client.GreetingResponse")
    @Action(input = "http://ws.iasri.com/Hello/greetingRequest", output = "http://ws.iasri.com/Hello/greetingResponse")
    public String greeting(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
